# Generated by Django 5.2.7 on 2025-10-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukaya_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartments/'),
        ),
    ]
