# Generated by Django 5.2.7 on 2025-10-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukaya_app', '0002_apartment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, help_text='Main display image', null=True, upload_to='apartments/'),
        ),
    ]
