# Generated by Django 5.2.7 on 2025-10-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukaya_app', '0003_alter_apartment_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='apartment_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='num_apartments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='num_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='num_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='offers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rooms_per_floor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='service_type',
            field=models.CharField(choices=[('standalone', 'Stand-alone'), ('ghorofa', 'Ghorofa')], default='standalone', max_length=20),
            preserve_default=False,
        ),
    ]
