# Generated by Django 5.2.7 on 2025-10-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukaya_app', '0004_apartment_apartment_names_apartment_num_apartments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_names',
            field=models.TextField(blank=True, help_text='Comma-separated apartment names', null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms_per_floor',
            field=models.TextField(blank=True, help_text='Comma-separated room counts per floor', null=True),
        ),
    ]
