# Generated by Django 5.2.7 on 2025-10-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukaya_app', '0005_alter_apartment_apartment_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='details',
        ),
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('hotel', 'Hotel'), ('office', 'Office')], default='apartment', max_length=50),
        ),
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='service_type',
            field=models.CharField(choices=[('standalone', 'Stand-alone'), ('ghorofa', 'Ghorofa')], default='standalone', max_length=20),
        ),
    ]
