# Generated by Django 5.2.7 on 2025-10-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukaya_app', '0006_remove_apartment_details_apartment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='description',
        ),
        migrations.AddField(
            model_name='apartment',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
