# Generated by Django 5.2.7 on 2025-10-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukaya_app', '0007_remove_apartment_description_apartment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('hotel', 'Hotel'), ('lodge', 'Lodge'), ('office', 'Office')], default='apartment', max_length=50),
        ),
    ]
