# Generated by Django 5.2.7 on 2025-10-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukaya_app', '0008_alter_apartment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
